
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// `engine` is not part of the strict PrismaConfig typings in some versions,
// cast to `any` to allow the classic engine to be used by the generated client.
const cfg: any = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
};

export default defineConfig(cfg as any);
